In [11]:
import numpy as np
#primal problem
A = [[1,1,1,0,0],
     [2,3,0,1,0],
     [1,5,0,0,1]]
b = [10,25,35]
c = [6,8,0,0,0]

In [12]:
#dual problem 
Ad = np.transpose(A)
bd = c
cd = b

In [13]:
print(Ad)
print(bd)
print(cd)

[[1 2 1]
 [1 3 5]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
[6, 8, 0, 0, 0]
[10, 25, 35]
